<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert(
            [
                ['id' => 1, 'region_id' => 1, 'name' => 'Adansi Asokwa', 'capital' => 'Adansi Asokwa'],
                ['id' => 2, 'region_id' => 1, 'name' => 'Adansi North', 'capital' => 'Fomena'],
                ['id' => 3, 'region_id' => 1, 'name' => 'Adansi South', 'capital' => 'New Edubiase'],
                ['id' => 4, 'region_id' => 1, 'name' => 'Afigya Kwabre North', 'capital' => 'Boamang'],
                ['id' => 5, 'region_id' => 1, 'name' => 'Afigya Kwabre South', 'capital' => 'Kodie'],
                ['id' => 6, 'region_id' => 1, 'name' => 'Ahafo Ano North Municipal', 'capital' => 'Tepa'],
                ['id' => 7, 'region_id' => 1, 'name' => 'Ahafo Ano South East', 'capital' => 'Adugyama'],
                ['id' => 8, 'region_id' => 1, 'name' => 'Ahafo Ano South West', 'capital' => 'Mankranso'],
                ['id' => 9, 'region_id' => 1, 'name' => 'Akrofuom', 'capital' => 'Akrofuom'],
                ['id' => 10, 'region_id' => 1, 'name' => 'Amansie Central', 'capital' => 'Jacobu'],
                ['id' => 11, 'region_id' => 1, 'name' => 'Amansie West 	Manso', 'capital' => 'Nkwanta'],
                ['id' => 12, 'region_id' => 1, 'name' => 'Amansie South', 'capital' => 'Manso Adubia'],
                ['id' => 13, 'region_id' => 1, 'name' => 'Asante Akim Central Municipal', 'capital' => 'Konongo'],
                ['id' => 14, 'region_id' => 1, 'name' => 'Asante Akim North', 'capital' => 'Agogo'],
                ['id' => 15, 'region_id' => 1, 'name' => 'Asante Akim South Municipal', 'capital' => 'Juaso'],
                ['id' => 16, 'region_id' => 1, 'name' => 'Asokore Mampong Municipal', 'capital' => 'Asokore Mampong'],
                ['id' => 17, 'region_id' => 1, 'name' => 'Asokwa Municipal', 'capital' => 'Asokwa'],
                ['id' => 18, 'region_id' => 1, 'name' => 'Atwima Kwanwoma', 'capital' => 'Twedie'],
                ['id' => 19, 'region_id' => 1, 'name' => 'Atwima Mponua', 'capital' => 'Nyinahin'],
                ['id' => 20, 'region_id' => 1, 'name' => 'Atwima Nwabiagya 	Municipal', 'capital' => 'Nkawie'],
                ['id' => 21, 'region_id' => 1, 'name' => 'Atwima Nwabiagya North', 'capital' => 'Barekese'],
                ['id' => 22, 'region_id' => 1, 'name' => 'Bekwai Municipal', 'capital' => 'Bekwai'],
                ['id' => 23, 'region_id' => 1, 'name' => 'Bosome Freho', 'capital' => 'Asiwa'],
                ['id' => 24, 'region_id' => 1, 'name' => 'Bosomtwe', 'capital' => 'Kuntanase'],
                ['id' => 25, 'region_id' => 1, 'name' => 'Ejisu Municipal', 'capital' => 'Ejisu'],
                ['id' => 26, 'region_id' => 1, 'name' => 'Ejura Sekyedumase Municipal', 'capital' => 'Ejura'],
                ['id' => 27, 'region_id' => 1, 'name' => 'Juaben Municipal', 'capital' => 'Juaben'],
                ['id' => 28, 'region_id' => 1, 'name' => 'Kumasi Metropolitan', 'capital' => 'Kumasi'],
                ['id' => 29, 'region_id' => 1, 'name' => 'Kwabre East Municipal', 'capital' => 'Mamponteng'],
                ['id' => 30, 'region_id' => 1, 'name' => 'Kwadaso Municipal', 'capital' => 'Kwadaso'],
                ['id' => 31, 'region_id' => 1, 'name' => 'Mampong Municipal', 'capital' => 'Mampong'],
                ['id' => 32, 'region_id' => 1, 'name' => 'Obuasi East Municipal', 'capital' => 'Tutuka'],
                ['id' => 33, 'region_id' => 1, 'name' => 'Obuasi Municipal', 'capital' => 'Obuasi'],
                ['id' => 34, 'region_id' => 1, 'name' => 'Offinso Municipal', 'capital' => 'Offinso'],
                ['id' => 35, 'region_id' => 1, 'name' => 'Offinso North', 'capital' => 'Akomadan'],
                ['id' => 36, 'region_id' => 1, 'name' => 'Oforikrom Municipal', 'capital' => 'Oforikrom'],
                ['id' => 37, 'region_id' => 1, 'name' => 'Old Tafo Municipal', 'capital' => 'Old Tafo'],
                ['id' => 38, 'region_id' => 1, 'name' => 'Sekyere Afram Plains', 'capital' => 'Drobonso'],
                ['id' => 39, 'region_id' => 1, 'name' => 'Sekyere Central', 'capital' => 'Nsuta'],
                ['id' => 40, 'region_id' => 1, 'name' => 'Sekyere East', 'capital' => 'Effiduase'],
                ['id' => 41, 'region_id' => 1, 'name' => 'Sekyere Kumawu', 'capital' => 'Kumawu'],
                ['id' => 42, 'region_id' => 1, 'name' => 'Sekyere South', 'capital' => 'Agona'],
                ['id' => 43, 'region_id' => 1, 'name' => 'Suame Municipal', 'capital' => 'Suame'],
                ['id' => 44, 'region_id' => 2, 'name' => 'Ablekuma Central Municipal', 'capital' => 'Lartebiokorshie'],
                ['id' => 45, 'region_id' => 2, 'name' => 'Ablekuma North Municipal', 'capital' => 'Darkuman'],
                ['id' => 46, 'region_id' => 2, 'name' => 'Ablekuma West Municipal', 'capital' => 'Dansoman'],
                ['id' => 47, 'region_id' => 2, 'name' => 'Accra Metropolitan', 'capital' => 'Accra'],
                ['id' => 48, 'region_id' => 2, 'name' => 'Ada East', 'capital' => 'Ada Foah'],
                ['id' => 49, 'region_id' => 2, 'name' => 'Ada West', 'capital' => 'Sege'],
                ['id' => 50, 'region_id' => 2, 'name' => 'Adenta Municipal', 'capital' => 'Adenta'],
                ['id' => 51, 'region_id' => 2, 'name' => 'Ashaiman Municipal', 'capital' => 'Ashaiman'],
                ['id' => 52, 'region_id' => 2, 'name' => 'Ayawaso Central Municipal', 'capital' => 'Kokomlemle'],
                ['id' => 53, 'region_id' => 2, 'name' => 'Ayawaso East Municipal', 'capital' => 'Nima'],
                ['id' => 54, 'region_id' => 2, 'name' => 'Ayawaso North Municipal', 'capital' => 'Accra New Town'],
                ['id' => 55, 'region_id' => 2, 'name' => 'Ayawaso West Municipal', 'capital' => 'Dzorwulu'],
                ['id' => 56, 'region_id' => 2, 'name' => 'Ga Central Municipal', 'capital' => 'Sowutuom'],
                ['id' => 57, 'region_id' => 2, 'name' => 'Ga East Municipal', 'capital' => 'Abokobi'],
                ['id' => 58, 'region_id' => 2, 'name' => 'Ga North Municipal', 'capital' => 'Amomole'],
                ['id' => 59, 'region_id' => 2, 'name' => 'Ga South Municipal', 'capital' => 'Ngleshie Amanfro'],
                ['id' => 60, 'region_id' => 2, 'name' => 'Ga West Municipal', 'capital' => 'Amasaman'],
                ['id' => 61, 'region_id' => 2, 'name' => 'Korle Klottey Municipal', 'capital' => 'Osu'],
                ['id' => 62, 'region_id' => 2, 'name' => 'Kpone Katamanso Municipal', 'capital' => 'Kpone'],
                ['id' => 63, 'region_id' => 2, 'name' => 'Krowor Municipal', 'capital' => 'Nungua'],
                ['id' => 64, 'region_id' => 2, 'name' => 'La Dade Kotopon Municipal', 'capital' => 'La'],
                ['id' => 65, 'region_id' => 2, 'name' => 'La Nkwantanang Madina Municipal', 'capital' => 'Madina'],
                ['id' => 66, 'region_id' => 2, 'name' => 'Ledzokuku Municipal', 'capital' => 'Teshie'],
                ['id' => 67, 'region_id' => 2, 'name' => 'Ningo Prampram', 'capital' => 'Prampram'],
                ['id' => 68, 'region_id' => 2, 'name' => 'Okaikwei North Municipal', 'capital' => 'Tesano'],
                ['id' => 69, 'region_id' => 2, 'name' => 'Shai Osudoku', 'capital' => 'Dodowa'],
                ['id' => 70, 'region_id' => 2, 'name' => 'Tema Metropolitan', 'capital' => 'Tema'],
                ['id' => 71, 'region_id' => 2, 'name' => 'Tema West Municipal', 'capital' => 'Tema Community 18'],
                ['id' => 72, 'region_id' => 2, 'name' => 'Weija Gbawe Municipal', 'capital' => 'Weija'],
                ['id' => 73, 'region_id' => 3, 'name' => 'Asunafo North Municipal', 'capital' => 'Goaso'],
                ['id' => 74, 'region_id' => 3, 'name' => 'Asunafo South', 'capital' => 'Kukuom'],
                ['id' => 75, 'region_id' => 3, 'name' => 'Asutifi North', 'capital' => 'Kenyasi'],
                ['id' => 76, 'region_id' => 3, 'name' => 'Asutifi South', 'capital' => 'Hwidiem'],
                ['id' => 77, 'region_id' => 3, 'name' => 'Tano North Municipal', 'capital' => 'Duayaw Nkwanta'],
                ['id' => 78, 'region_id' => 3, 'name' => 'Tano South Municipal', 'capital' => 'Bechem'],
                ['id' => 79, 'region_id' => 4, 'name' => 'Banda', 'capital' => 'Banda Ahenkro'],
                ['id' => 80, 'region_id' => 4, 'name' => 'Berekum East Municipal', 'capital' => 'Berekum'],
                ['id' => 81, 'region_id' => 4, 'name' => 'Berekum West', 'capital' => 'Jinijini'],
                ['id' => 82, 'region_id' => 4, 'name' => 'Dormaa Central Municipal', 'capital' => 'Dormaa Ahenkro'],
                ['id' => 83, 'region_id' => 4, 'name' => 'Dormaa East', 'capital' => 'Wamfie'],
                ['id' => 84, 'region_id' => 4, 'name' => 'Dormaa West', 'capital' => 'Nkrankwanta'],
                ['id' => 85, 'region_id' => 4, 'name' => 'Jaman North', 'capital' => 'Sampa'],
                ['id' => 86, 'region_id' => 4, 'name' => 'Jaman South Municipal', 'capital' => 'Drobo'],
                ['id' => 87, 'region_id' => 4, 'name' => 'Sunyani Municipal', 'capital' => 'Sunyani'],
                ['id' => 88, 'region_id' => 4, 'name' => 'Sunyani West', 'capital' => 'Odumase'],
                ['id' => 89, 'region_id' => 4, 'name' => 'Tain', 'capital' => 'Nsawkaw'],
                ['id' => 90, 'region_id' => 4, 'name' => 'Wenchi Municipal', 'capital' => 'Wenchi'],
                ['id' => 91, 'region_id' => 5, 'name' => 'Atebubu Amantin Municipal', 'capital' => 'Atebubu'],
                ['id' => 92, 'region_id' => 5, 'name' => 'Kintampo North Municipal', 'capital' => 'Kintampo'],
                ['id' => 93, 'region_id' => 5, 'name' => 'Kintampo South', 'capital' => 'Jema'],
                ['id' => 94, 'region_id' => 5, 'name' => 'Nkoranza North', 'capital' => 'Busunya'],
                ['id' => 95, 'region_id' => 5, 'name' => 'Nkoranza South Municipal', 'capital' => 'Nkoranza'],
                ['id' => 96, 'region_id' => 5, 'name' => 'Pru East', 'capital' => 'Yeji'],
                ['id' => 97, 'region_id' => 5, 'name' => 'Pru West', 'capital' => 'Prang'],
                ['id' => 98, 'region_id' => 5, 'name' => 'Sene East', 'capital' => 'Kajaji'],
                ['id' => 99, 'region_id' => 5, 'name' => 'Sene West Kwame', 'capital' => 'Danso'],
                ['id' => 100, 'region_id' => 5, 'name' => 'Techiman Municipal', 'capital' => 'Techiman'],
                ['id' => 101, 'region_id' => 5, 'name' => 'Techiman North', 'capital' => 'Tuobodom'],
                ['id' => 102, 'region_id' => 6, 'name' => 'Abura Asebu Kwamankese', 'capital' => 'Abura Dunkwa'],
                ['id' => 103, 'region_id' => 6, 'name' => 'Agona East', 'capital' => 'Nsaba'],
                ['id' => 104, 'region_id' => 6, 'name' => 'Agona West Municipal', 'capital' => 'Agona Swedru'],
                ['id' => 105, 'region_id' => 6, 'name' => 'Ajumako Enyan Essiam', 'capital' => 'Ajumako'],
                ['id' => 106, 'region_id' => 6, 'name' => 'Asikuma Odoben Brakwa', 'capital' => 'Breman Asikuma'],
                ['id' => 107, 'region_id' => 6, 'name' => 'Assin Central Municipal', 'capital' => 'Assin Foso'],
                ['id' => 108, 'region_id' => 6, 'name' => 'Assin North', 'capital' => 'Assin Bereku'],
                ['id' => 109, 'region_id' => 6, 'name' => 'Assin South', 'capital' => 'Nsuaem Kyekyewere'],
                ['id' => 110, 'region_id' => 6, 'name' => 'Awutu Senya East Municipal', 'capital' => 'Kasoa'],
                ['id' => 111, 'region_id' => 6, 'name' => 'Awutu Senya West', 'capital' => 'Awutu Breku'],
                ['id' => 112, 'region_id' => 6, 'name' => 'Cape Coast Metropolitan ', 'capital' => 'Cape Coast'],
                ['id' => 113, 'region_id' => 6, 'name' => 'Effutu Municipal', 'capital' => 'Winneba'],
                ['id' => 114, 'region_id' => 6, 'name' => 'Ekumfi', 'capital' => 'Esakyir'],
                ['id' => 115, 'region_id' => 6, 'name' => 'Gomoa East', 'capital' => 'Potsin'],
                ['id' => 116, 'region_id' => 6, 'name' => 'Gomoa Central', 'capital' => 'Afransi'],
                ['id' => 117, 'region_id' => 6, 'name' => 'Gomoa West', 'capital' => 'Apam'],
                ['id' => 118, 'region_id' => 6, 'name' => 'Komenda Edina Eguafo Abirem Municipal', 'capital' => 'Elmina'],
                ['id' => 119, 'region_id' => 6, 'name' => 'Mfantsiman Municipal', 'capital' => 'Saltpond'],
                ['id' => 120, 'region_id' => 6, 'name' => 'Twifo Atti Morkwa Twifo', 'capital' => 'Praso'],
                ['id' => 121, 'region_id' => 6, 'name' => 'Twifo Hemang Lower Denkyira', 'capital' => 'Hemang'],
                ['id' => 122, 'region_id' => 6, 'name' => 'Upper Denkyira East Municipal', 'capital' => 'Dunkwa on Offin'],
                ['id' => 123, 'region_id' => 6, 'name' => 'Upper Denkyira West', 'capital' => 'Diaso'],
                ['id' => 124, 'region_id' => 7, 'name' => 'Abuakwa North Municipal', 'capital' => 'Kukurantumi'],
                ['id' => 125, 'region_id' => 7, 'name' => 'Abuakwa South Municipal', 'capital' => 'Kibi'],
                ['id' => 126, 'region_id' => 7, 'name' => 'Achiase', 'capital' => 'Achiase'],
                ['id' => 127, 'region_id' => 7, 'name' => 'Akuapim North Municipal', 'capital' => 'Akropong'],
                ['id' => 128, 'region_id' => 7, 'name' => 'Akuapim South', 'capital' => 'Aburi'],
                ['id' => 129, 'region_id' => 7, 'name' => 'Akyemansa', 'capital' => 'Ofoase'],
                ['id' => 130, 'region_id' => 7, 'name' => 'Asene Manso Akroso', 'capital' => 'Manso'],
                ['id' => 131, 'region_id' => 7, 'name' => 'Asuogyaman', 'capital' => 'Atimpoku'],
                ['id' => 132, 'region_id' => 7, 'name' => 'Atiwa East', 'capital' => 'Anyinam'],
                ['id' => 133, 'region_id' => 7, 'name' => 'Atiwa West', 'capital' => 'Kwabeng'],
                ['id' => 134, 'region_id' => 7, 'name' => 'Ayensuano', 'capital' => 'Coaltar'],
                ['id' => 135, 'region_id' => 7, 'name' => 'Birim Central Municipal', 'capital' => 'Akim Oda'],
                ['id' => 136, 'region_id' => 7, 'name' => 'Birim North', 'capital' => 'New Abirem'],
                ['id' => 137, 'region_id' => 7, 'name' => 'Birim South', 'capital' => 'Akim Swedru'],
                ['id' => 138, 'region_id' => 7, 'name' => 'Denkyembour', 'capital' => 'Akwatia'],
                ['id' => 139, 'region_id' => 7, 'name' => 'Fanteakwa North', 'capital' => 'Begoro'],
                ['id' => 140, 'region_id' => 7, 'name' => 'Fanteakwa South', 'capital' => 'Osino'],
                ['id' => 141, 'region_id' => 7, 'name' => 'Kwaebibirem Municipal', 'capital' => 'Kade'],
                ['id' => 142, 'region_id' => 7, 'name' => 'Kwahu Afram Plains North', 'capital' => 'Donkorkrom'],
                ['id' => 143, 'region_id' => 7, 'name' => 'Kwahu Afram Plains South', 'capital' => 'Tease'],
                ['id' => 144, 'region_id' => 7, 'name' => 'Kwahu East', 'capital' => 'Abetifi'],
                ['id' => 145, 'region_id' => 7, 'name' => 'Kwahu South', 'capital' => 'Mpraeso'],
                ['id' => 146, 'region_id' => 7, 'name' => 'Kwahu West Municipal', 'capital' => 'Nkawkaw'],
                ['id' => 147, 'region_id' => 7, 'name' => 'Lower Manya Krobo Municipal', 'capital' => 'Krobo Odumase'],
                ['id' => 148, 'region_id' => 7, 'name' => 'New Juaben North Municipal', 'capital' => 'Effiduase'],
                ['id' => 149, 'region_id' => 7, 'name' => 'New Juaben South Municipal', 'capital' => 'Koforidua'],
                ['id' => 150, 'region_id' => 7, 'name' => 'Nsawam Adoagyire Municipal', 'capital' => 'Nsawam'],
                ['id' => 151, 'region_id' => 7, 'name' => 'Okere', 'capital' => 'Adukrom'],
                ['id' => 152, 'region_id' => 7, 'name' => 'Suhum Municipal', 'capital' => 'Suhum'],
                ['id' => 153, 'region_id' => 7, 'name' => 'Upper Manya Krobo', 'capital' => 'Asesewa'],
                ['id' => 154, 'region_id' => 7, 'name' => 'Upper West', 'capital' => 'Akim Adeiso'],
                ['id' => 155, 'region_id' => 7, 'name' => 'West Akim Municipal', 'capital' => 'Asamankese'],
                ['id' => 156, 'region_id' => 7, 'name' => 'Yilo Krobo Municipal', 'capital' => 'Somanya'],
                ['id' => 157, 'region_id' => 8, 'name' => 'Bunkpurugu Nyankpanduri', 'capital' => 'Bunkpurugu'],
                ['id' => 158, 'region_id' => 8, 'name' => 'Chereponi', 'capital' => 'Chereponi'],
                ['id' => 159, 'region_id' => 8, 'name' => 'East Mamprusi Municipal', 'capital' => 'Gambaga'],
                ['id' => 160, 'region_id' => 8, 'name' => 'Mamprugu Moagduri', 'capital' => 'Yagaba'],
                ['id' => 161, 'region_id' => 8, 'name' => 'West Mamprusi Municipal', 'capital' => 'Walewale'],
                ['id' => 162, 'region_id' => 8, 'name' => 'Yunyoo Nasuan', 'capital' => 'Yunyoo'],
                ['id' => 163, 'region_id' => 9, 'name' => 'Gushegu Municipal', 'capital' => 'Gushegu'],
                ['id' => 164, 'region_id' => 9, 'name' => 'Karaga', 'capital' => 'Karaga'],
                ['id' => 165, 'region_id' => 9, 'name' => 'Kpandai', 'capital' => 'Kpandai'],
                ['id' => 166, 'region_id' => 9, 'name' => 'Kumbungu', 'capital' => 'Kumbungu'],
                ['id' => 167, 'region_id' => 9, 'name' => 'Mion', 'capital' => 'Sang'],
                ['id' => 168, 'region_id' => 9, 'name' => 'Nanton', 'capital' => 'Nanton'],
                ['id' => 169, 'region_id' => 9, 'name' => 'Nanumba North Municipal', 'capital' => 'Bimbilla'],
                ['id' => 170, 'region_id' => 9, 'name' => 'Nanumba South', 'capital' => 'Wulensi'],
                ['id' => 171, 'region_id' => 9, 'name' => 'Saboba', 'capital' => 'Saboba'],
                ['id' => 172, 'region_id' => 9, 'name' => 'Sagnarigu Municipal', 'capital' => 'Sagnarigu'],
                ['id' => 173, 'region_id' => 9, 'name' => 'Savelugu Municipal', 'capital' => 'Savelugu'],
                ['id' => 174, 'region_id' => 9, 'name' => 'Tamale Metropolitan', 'capital' => 'Tamale'],
                ['id' => 175, 'region_id' => 9, 'name' => 'Tatale Sanguli', 'capital' => 'Tatale'],
                ['id' => 176, 'region_id' => 9, 'name' => 'Tolon', 'capital' => 'Tolon'],
                ['id' => 177, 'region_id' => 9, 'name' => 'Yendi Municipal', 'capital' => 'Yendi'],
                ['id' => 178, 'region_id' => 9, 'name' => 'Zabzug', 'capital' => 'Zabzugu'],
                ['id' => 179, 'region_id' => 10, 'name' => 'Biakoye', 'capital' => 'Nkonya Ahenkro'],
                ['id' => 180, 'region_id' => 10, 'name' => 'Guan', 'capital' => 'Likpe Mate'],
                ['id' => 181, 'region_id' => 10, 'name' => 'Jasikan', 'capital' => 'Jasikan'],
                ['id' => 182, 'region_id' => 10, 'name' => 'Kadjebi', 'capital' => 'Kadjebi'],
                ['id' => 183, 'region_id' => 10, 'name' => 'Krachi East Municipal', 'capital' => 'Dambai'],
                ['id' => 184, 'region_id' => 10, 'name' => 'Krachi Nchumuru', 'capital' => 'Chinderi'],
                ['id' => 185, 'region_id' => 10, 'name' => 'Krachi West', 'capital' => 'Kete Krachi'],
                ['id' => 186, 'region_id' => 10, 'name' => 'Nkwanta North', 'capital' => 'Kpassa'],
                ['id' => 187, 'region_id' => 10, 'name' => 'Nkwanta South Municipal', 'capital' => 'Nkwanta'],
                ['id' => 188, 'region_id' => 11, 'name' => 'Bole', 'capital' => 'Bole'],
                ['id' => 189, 'region_id' => 11, 'name' => 'Central Gonja', 'capital' => 'Buipe'],
                ['id' => 190, 'region_id' => 11, 'name' => 'East Gonja Municipal', 'capital' => 'Salaga'],
                ['id' => 191, 'region_id' => 11, 'name' => 'North Gonja', 'capital' => 'Daboya'],
                ['id' => 192, 'region_id' => 11, 'name' => 'North East Gonja', 'capital' => 'Kpalbe'],
                ['id' => 193, 'region_id' => 11, 'name' => 'Sawla Tuna Kalba', 'capital' => 'Sawla'],
                ['id' => 194, 'region_id' => 11, 'name' => 'West Gonja Municipal', 'capital' => 'Damongo'],
                ['id' => 195, 'region_id' => 12, 'name' => 'Bawku Municipal', 'capital' => 'Bawku'],
                ['id' => 196, 'region_id' => 12, 'name' => 'Bawku West', 'capital' => 'Zebilla'],
                ['id' => 197, 'region_id' => 12, 'name' => 'Binduri', 'capital' => 'Binduri'],
                ['id' => 198, 'region_id' => 12, 'name' => 'Bolgatanga East', 'capital' => 'Zuarungu'],
                ['id' => 199, 'region_id' => 12, 'name' => 'Bolgatanga Municipal', 'capital' => 'Bolgatanga'],
                ['id' => 200, 'region_id' => 12, 'name' => 'Bongo', 'capital' => 'Bongo'],
                ['id' => 201, 'region_id' => 12, 'name' => 'Builsa North Municipal', 'capital' => 'Sandema'],
                ['id' => 202, 'region_id' => 12, 'name' => 'Builsa South', 'capital' => 'Fumbisi'],
                ['id' => 203, 'region_id' => 12, 'name' => 'Garu', 'capital' => 'Garu'],
                ['id' => 204, 'region_id' => 12, 'name' => 'Kassena Nankana Municipal', 'capital' => 'Navrongo'],
                ['id' => 205, 'region_id' => 12, 'name' => 'Kassena Nankana West', 'capital' => 'Paga'],
                ['id' => 206, 'region_id' => 12, 'name' => 'Nabdam', 'capital' => 'Nangodi'],
                ['id' => 207, 'region_id' => 12, 'name' => 'Pusiga', 'capital' => 'Pusiga'],
                ['id' => 208, 'region_id' => 12, 'name' => 'Talensi', 'capital' => 'Tongo'],
                ['id' => 209, 'region_id' => 12, 'name' => 'Tempane', 'capital' => 'Tempane'],
                ['id' => 210, 'region_id' => 13, 'name' => 'Daffiama Bussie Issa', 'capital' => 'Issa'],
                ['id' => 211, 'region_id' => 13, 'name' => 'Jirapa Municipal', 'capital' => 'Jirapa'],
                ['id' => 212, 'region_id' => 13, 'name' => 'Lambussie Karni', 'capital' => 'Lambussie'],
                ['id' => 213, 'region_id' => 13, 'name' => 'Lawra Municipal', 'capital' => 'Lawra'],
                ['id' => 214, 'region_id' => 13, 'name' => 'Nadowli Kaleo', 'capital' => 'Nadowli'],
                ['id' => 215, 'region_id' => 13, 'name' => 'Nandom Municipal', 'capital' => 'Nandom'],
                ['id' => 216, 'region_id' => 13, 'name' => 'Sissala East Municipal', 'capital' => 'Tumu'],
                ['id' => 217, 'region_id' => 13, 'name' => 'Sissala West', 'capital' => 'Gwollu'],
                ['id' => 218, 'region_id' => 13, 'name' => 'Wa East', 'capital' => 'Funsi'],
                ['id' => 219, 'region_id' => 13, 'name' => 'Wa Municipal', 'capital' => 'Wa'],
                ['id' => 220, 'region_id' => 13, 'name' => 'Wa West', 'capital' => 'Wechiau'],
                ['id' => 221, 'region_id' => 14, 'name' => 'Adaklu', 'capital' => 'Adaklu Waya'],
                ['id' => 222, 'region_id' => 14, 'name' => 'Afadzato South', 'capital' => 'Ve Golokwati'],
                ['id' => 223, 'region_id' => 14, 'name' => 'Agotime Ziope', 'capital' => 'Kpetoe'],
                ['id' => 224, 'region_id' => 14, 'name' => 'Akatsi North', 'capital' => 'Ave Dakpa'],
                ['id' => 225, 'region_id' => 14, 'name' => 'Akatsi South', 'capital' => 'Akatsi'],
                ['id' => 226, 'region_id' => 14, 'name' => 'Anloga', 'capital' => 'Anloga'],
                ['id' => 227, 'region_id' => 14, 'name' => 'Central Tongu', 'capital' => 'Adidome'],
                ['id' => 228, 'region_id' => 14, 'name' => 'Ho Municipal', 'capital' => 'Ho'],
                ['id' => 229, 'region_id' => 14, 'name' => 'Ho West', 'capital' => 'Dzolokpuita'],
                ['id' => 230, 'region_id' => 14, 'name' => 'Hohoe Municipal', 'capital' => 'Hohoe'],
                ['id' => 231, 'region_id' => 14, 'name' => 'Keta Municipal', 'capital' => 'Keta'],
                ['id' => 232, 'region_id' => 14, 'name' => 'Ketu North Municipal', 'capital' => 'Dzodze'],
                ['id' => 233, 'region_id' => 14, 'name' => 'Ketu South Municipal', 'capital' => 'Denu'],
                ['id' => 234, 'region_id' => 14, 'name' => 'Kpando Municipal', 'capital' => 'Kpando'],
                ['id' => 235, 'region_id' => 14, 'name' => 'North Dayi', 'capital' => 'Anfoega'],
                ['id' => 236, 'region_id' => 14, 'name' => 'North Tongu', 'capital' => 'Battor Dugame'],
                ['id' => 237, 'region_id' => 14, 'name' => 'South Dayi', 'capital' => 'Kpeve'],
                ['id' => 238, 'region_id' => 14, 'name' => 'South Tongu', 'capital' => 'Sogakope'],
                ['id' => 239, 'region_id' => 15, 'name' => 'Ahanta West Municipal', 'capital' => 'Agona Ahanta'],
                ['id' => 240, 'region_id' => 15, 'name' => 'Amenfi Central', 'capital' => 'Manso Amenfi'],
                ['id' => 241, 'region_id' => 15, 'name' => 'Amenfi West Municipal', 'capital' => 'Asankragua'],
                ['id' => 242, 'region_id' => 15, 'name' => 'Effia Kwesimintsim Municipal', 'capital' => 'Kwesimintsim'],
                ['id' => 243, 'region_id' => 15, 'name' => 'Ellembelle', 'capital' => 'Nkroful'],
                ['id' => 244, 'region_id' => 15, 'name' => 'Jomoro Municipal', 'capital' => 'Half Assini'],
                ['id' => 245, 'region_id' => 15, 'name' => 'Mpohor', 'capital' => 'Mpohor'],
                ['id' => 246, 'region_id' => 15, 'name' => 'Nzema East Municipal', 'capital' => 'Axim'],
                ['id' => 247, 'region_id' => 15, 'name' => 'Prestea-Huni Valley Municipal', 'capital' => 'Prestea'],
                ['id' => 248, 'region_id' => 15, 'name' => 'Sekondi Takoradi Metropolitan', 'capital' => 'Sekondi-Takoradi'],
                ['id' => 249, 'region_id' => 15, 'name' => 'Shama', 'capital' => 'Shama'],
                ['id' => 250, 'region_id' => 15, 'name' => 'Tarkwa-Nsuaem Municipal', 'capital' => 'Tarkwa'],
                ['id' => 251, 'region_id' => 15, 'name' => 'Wassa Amenfi East Municipal', 'capital' => 'Wassa-Akropong'],
                ['id' => 252, 'region_id' => 15, 'name' => 'Wassa East', 'capital' => 'Daboase'],
                ['id' => 253, 'region_id' => 16, 'name' => 'Aowin Municipal', 'capital' => 'Enchi'],
                ['id' => 254, 'region_id' => 16, 'name' => 'Bia East', 'capital' => 'Sefwi Adabokrom'],
                ['id' => 255, 'region_id' => 16, 'name' => 'Bia West', 'capital' => 'Essam Debiso'],
                ['id' => 256, 'region_id' => 16, 'name' => 'Bibiani Anhwiaso Bekwai Municipal', 'capital' => 'Bibiani'],
                ['id' => 257, 'region_id' => 16, 'name' => 'Bodi', 'capital' => 'Sefwi Bodi'],
                ['id' => 258, 'region_id' => 16, 'name' => 'Juaboso', 'capital' => 'Juaboso'],
                ['id' => 259, 'region_id' => 16, 'name' => 'Sefwi Akontombra', 'capital' => 'Sefwi Akontombra'],
                ['id' => 260, 'region_id' => 16, 'name' => 'Sefwi Wiawso Municipal', 'capital' => 'Sefwi Wiawso'],
                ['id' => 261, 'region_id' => 16, 'name' => 'Suaman', 'capital' => 'Dadieso'],
            ]
        );
    }
}
