<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert(
            [
                ['region_id' => 1, 'name' => 'Adansi Asokwa', 'capital' => 'Adansi Asokwa'],
                ['region_id' => 1, 'name' => 'Adansi North', 'capital' => 'Fomena'],
                ['region_id' => 1, 'name' => 'Adansi South', 'capital' => 'New Edubiase'],
                ['region_id' => 1, 'name' => 'Afigya Kwabre North', 'capital' => 'Boamang'],
                ['region_id' => 1, 'name' => 'Afigya Kwabre South', 'capital' => 'Kodie'],
                ['region_id' => 1, 'name' => 'Ahafo Ano North Municipal', 'capital' => 'Tepa'],
                ['region_id' => 1, 'name' => 'Ahafo Ano South East', 'capital' => 'Adugyama'],
                ['region_id' => 1, 'name' => 'Ahafo Ano South West', 'capital' => 'Mankranso'],
                ['region_id' => 1, 'name' => 'Akrofuom', 'capital' => 'Akrofuom'],
                ['region_id' => 1, 'name' => 'Amansie Central', 'capital' => 'Jacobu'],
                ['region_id' => 1, 'name' => 'Amansie West 	Manso', 'capital' => 'Nkwanta'],
                ['region_id' => 1, 'name' => 'Amansie South', 'capital' => 'Manso Adubia'],
                ['region_id' => 1, 'name' => 'Asante Akim Central Municipal', 'capital' => ' 	Konongo'],
                ['region_id' => 1, 'name' => 'Asante Akim North', 'capital' => 'Agogo'],
                ['region_id' => 1, 'name' => 'Asante Akim South Municipal', 'capital' => ' Juaso'],
                ['region_id' => 1, 'name' => 'Asokore Mampong Municipal', 'capital' => 'Asokore Mampong'],
                ['region_id' => 1, 'name' => 'Asokwa Municipal', 'capital' => 'Asokwa'],
                ['region_id' => 1, 'name' => 'Atwima Kwanwoma', 'capital' => 'Twedie'],
                ['region_id' => 1, 'name' => 'Atwima Mponua', 'capital' => 'Nyinahin'],
                ['region_id' => 1, 'name' => 'Atwima Nwabiagya 	Municipal', 'capital' => 'Nkawie'],
                ['region_id' => 1, 'name' => 'Atwima Nwabiagya North', 'capital' => 'Barekese'],
                ['region_id' => 1, 'name' => 'Bekwai Municipal', 'capital' => 'Bekwai'],
                ['region_id' => 1, 'name' => 'Bosome Freho', 'capital' => 'Asiwa'],
                ['region_id' => 1, 'name' => 'Bosomtwe', 'capital' => 'Kuntanase'],
                ['region_id' => 1, 'name' => 'Ejisu Municipal', 'capital' => 'Ejisu'],
                ['region_id' => 1, 'name' => 'Ejura Sekyedumase Municipal', 'capital' => 'Ejura'],
                ['region_id' => 1, 'name' => 'Juaben Municipal', 'capital' => 'Juaben'],
                ['region_id' => 1, 'name' => 'Kumasi Metropolitan', 'capital' => 'Kumasi'],
                ['region_id' => 1, 'name' => 'Kwabre East Municipal', 'capital' => 'Mamponteng'],
                ['region_id' => 1, 'name' => 'Kwadaso Municipal', 'capital' => 'Kwadaso'],
                ['region_id' => 1, 'name' => 'Mampong Municipal', 'capital' => 'Mampong'],
                ['region_id' => 1, 'name' => 'Obuasi East Municipal', 'capital' => 'Tutuka'],
                ['region_id' => 1, 'name' => 'Obuasi Municipal', 'capital' => 'Obuasi'],
                ['region_id' => 1, 'name' => 'Offinso Municipal', 'capital' => 'Offinso'],
                ['region_id' => 1, 'name' => 'Offinso North', 'capital' => 'Akomadan'],
                ['region_id' => 1, 'name' => 'Oforikrom Municipal', 'capital' => 'Oforikrom'],
                ['region_id' => 1, 'name' => 'Old Tafo Municipal', 'capital' => 'Old Tafo'],
                ['region_id' => 1, 'name' => 'Sekyere Afram Plains', 'capital' => 'Drobonso'],
                ['region_id' => 1, 'name' => 'Sekyere Central', 'capital' => 'Nsuta'],
                ['region_id' => 1, 'name' => 'Sekyere East', 'capital' => 'Effiduase'],
                ['region_id' => 1, 'name' => 'Sekyere Kumawu', 'capital' => 'Kumawu'],
                ['region_id' => 1, 'name' => 'Sekyere South', 'capital' => 'Agona'],
                ['region_id' => 1, 'name' => 'Suame Municipal', 'capital' => 'Suame'],
                ['region_id' => 2, 'name' => 'Ablekuma Central Municipal', 'capital' => 'Lartebiokorshie'],
                ['region_id' => 2, 'name' => 'Ablekuma North Municipal', 'capital' => 'Darkuman'],
                ['region_id' => 2, 'name' => 'Ablekuma West Municipal', 'capital' => 'Dansoman'],
                ['region_id' => 2, 'name' => 'Accra Metropolitan', 'capital' => 'Accra'],
                ['region_id' => 2, 'name' => 'Ada East', 'capital' => 'Ada Foah'],
                ['region_id' => 2, 'name' => 'Ada West', 'capital' => 'Sege'],
                ['region_id' => 2, 'name' => 'Adenta Municipal', 'capital' => 'Adenta'],
                ['region_id' => 2, 'name' => 'Ashaiman Municipal', 'capital' => 'Ashaiman'],
                ['region_id' => 2, 'name' => 'Ayawaso Central Municipal', 'capital' => 'Kokomlemle'],
                ['region_id' => 2, 'name' => 'Ayawaso East Municipal', 'capital' => 'Nima'],
                ['region_id' => 2, 'name' => 'Ayawaso North Municipal', 'capital' => 'Accra New Town'],
                ['region_id' => 2, 'name' => 'Ayawaso West Municipal', 'capital' => 'Dzorwulu'],
                ['region_id' => 2, 'name' => 'Ga Central Municipal', 'capital' => 'Sowutuom'],
                ['region_id' => 2, 'name' => 'Ga East Municipal', 'capital' => 'Abokobi'],
                ['region_id' => 2, 'name' => 'Ga North Municipal', 'capital' => 'Amomole'],
                ['region_id' => 2, 'name' => 'Ga South Municipal', 'capital' => 'Ngleshie Amanfro'],
                ['region_id' => 2, 'name' => 'Ga West Municipal', 'capital' => 'Amasaman'],
                ['region_id' => 2, 'name' => 'Korle Klottey Municipal', 'capital' => 'Osu'],
                ['region_id' => 2, 'name' => 'Kpone Katamanso Municipal', 'capital' => 'Kpone'],
                ['region_id' => 2, 'name' => 'Krowor Municipal', 'capital' => 'Nungua'],
                ['region_id' => 2, 'name' => 'La Dade Kotopon Municipal', 'capital' => 'La'],
                ['region_id' => 2, 'name' => 'La Nkwantanang Madina Municipal', 'capital' => 'Madina'],
                ['region_id' => 2, 'name' => 'Ledzokuku Municipal', 'capital' => 'Teshie'],
                ['region_id' => 2, 'name' => 'Ningo Prampram', 'capital' => 'Prampram'],
                ['region_id' => 2, 'name' => 'Okaikwei North Municipal', 'capital' => 'Tesano'],
                ['region_id' => 2, 'name' => 'Shai Osudoku', 'capital' => 'Dodowa'],
                ['region_id' => 2, 'name' => 'Tema Metropolitan', 'capital' => 'Tema'],
                ['region_id' => 2, 'name' => 'Tema West Municipal', 'capital' => 'Tema Community 18'],
                ['region_id' => 2, 'name' => 'Weija Gbawe Municipal', 'capital' => 'Weija'],
                ['region_id' => 3, 'name' => 'Asunafo North Municipal', 'capital' => 'Goaso'],
                ['region_id' => 3, 'name' => 'Asunafo South', 'capital' => 'Kukuom'],
                ['region_id' => 3, 'name' => 'Asutifi North', 'capital' => 'Kenyasi'],
                ['region_id' => 3, 'name' => 'Asutifi South', 'capital' => 'Hwidiem'],
                ['region_id' => 3, 'name' => 'Tano North Municipal', 'capital' => 'Duayaw Nkwanta'],
                ['region_id' => 3, 'name' => 'Tano South Municipal', 'capital' => 'Bechem'],
                ['region_id' => 4, 'name' => 'Banda', 'capital' => 'Banda Ahenkro'],
                ['region_id' => 4, 'name' => 'Berekum East Municipal', 'capital' => 'Berekum'],
                ['region_id' => 4, 'name' => 'Berekum West', 'capital' => 'Jinijini'],
                ['region_id' => 4, 'name' => 'Dormaa Central Municipal', 'capital' => 'Dormaa Ahenkro'],
                ['region_id' => 4, 'name' => 'Dormaa East', 'capital' => 'Wamfie'],
                ['region_id' => 4, 'name' => 'Dormaa West', 'capital' => 'Nkrankwanta'],
                ['region_id' => 4, 'name' => 'Jaman North', 'capital' => 'Sampa'],
                ['region_id' => 4, 'name' => 'Jaman South Municipal', 'capital' => 'Drobo'],
                ['region_id' => 4, 'name' => 'Sunyani Municipal', 'capital' => 'Sunyani'],
                ['region_id' => 4, 'name' => 'Sunyani West', 'capital' => 'Odumase'],
                ['region_id' => 4, 'name' => 'Tain', 'capital' => 'Nsawkaw'],
                ['region_id' => 4, 'name' => 'Wenchi Municipal', 'capital' => 'Wenchi'],
                ['region_id' => 5, 'name' => 'Atebubu Amantin Municipal', 'capital' => 'Atebubu'],
                ['region_id' => 5, 'name' => 'Kintampo North Municipal', 'capital' => 'Kintampo'],
                ['region_id' => 5, 'name' => 'Kintampo South', 'capital' => 'Jema'],
                ['region_id' => 5, 'name' => 'Nkoranza North', 'capital' => 'Busunya'],
                ['region_id' => 5, 'name' => 'Nkoranza South Municipal', 'capital' => 'Nkoranza'],
                ['region_id' => 5, 'name' => 'Pru East', 'capital' => 'Yeji'],
                ['region_id' => 5, 'name' => 'Pru West', 'capital' => 'Prang'],
                ['region_id' => 5, 'name' => 'Sene East', 'capital' => 'Kajaji'],
                ['region_id' => 5, 'name' => 'Sene West Kwame', 'capital' => 'Danso'],
                ['region_id' => 5, 'name' => 'Techiman Municipal', 'capital' => 'Techiman'],
                ['region_id' => 5, 'name' => 'Techiman North', 'capital' => 'Tuobodom'],
                ['region_id' => 6, 'name' => 'Abura Asebu Kwamankese', 'capital' => 'Abura Dunkwa'],
                ['region_id' => 6, 'name' => 'Agona East', 'capital' => 'Nsaba'],
                ['region_id' => 6, 'name' => 'Agona West Municipal', 'capital' => 'Agona Swedru'],
                ['region_id' => 6, 'name' => 'Ajumako Enyan Essiam', 'capital' => 'Ajumako'],
                ['region_id' => 6, 'name' => 'Asikuma Odoben Brakwa', 'capital' => 'Breman Asikuma'],
                ['region_id' => 6, 'name' => 'Assin Central Municipal', 'capital' => 'Assin Foso'],
                ['region_id' => 6, 'name' => 'Assin North', 'capital' => 'Assin Bereku'],
                ['region_id' => 6, 'name' => 'Assin South', 'capital' => 'Nsuaem Kyekyewere'],
                ['region_id' => 6, 'name' => 'Awutu Senya East Municipal', 'capital' => 'Kasoa'],
                ['region_id' => 6, 'name' => 'Awutu Senya West', 'capital' => 'Awutu Breku'],
                ['region_id' => 6, 'name' => 'Cape Coast Metropolitan ', 'capital' => 'Cape Coast'],
                ['region_id' => 6, 'name' => 'Effutu Municipal', 'capital' => 'Winneba'],
                ['region_id' => 6, 'name' => 'Ekumfi', 'capital' => 'Esakyir'],
                ['region_id' => 6, 'name' => 'Gomoa East', 'capital' => 'Potsin'],
                ['region_id' => 6, 'name' => 'Gomoa Central', 'capital' => 'Afransi'],
                ['region_id' => 6, 'name' => 'Gomoa West', 'capital' => 'Apam'],
                ['region_id' => 6, 'name' => 'Komenda Edina Eguafo Abirem Municipal', 'capital' => 'Elmina'],
                ['region_id' => 6, 'name' => 'Mfantsiman Municipal', 'capital' => 'Saltpond'],
                ['region_id' => 6, 'name' => 'Twifo Atti Morkwa Twifo', 'capital' => 'Praso'],
                ['region_id' => 6, 'name' => 'Twifo Hemang Lower Denkyira', 'capital' => 'Hemang'],
                ['region_id' => 6, 'name' => 'Upper Denkyira East Municipal', 'capital' => 'Dunkwa on Offin'],
                ['region_id' => 6, 'name' => 'Upper Denkyira West', 'capital' => 'Diaso'],
                ['region_id' => 7, 'name' => 'Abuakwa North Municipal', 'capital' => 'Kukurantumi'],
                ['region_id' => 7, 'name' => 'Abuakwa South Municipal', 'capital' => 'Kibi'],
                ['region_id' => 7, 'name' => 'Achiase', 'capital' => 'Achiase'],
                ['region_id' => 7, 'name' => 'Akuapim North Municipal', 'capital' => 'Akropong'],
                ['region_id' => 7, 'name' => 'Akuapim South', 'capital' => 'Aburi'],
                ['region_id' => 7, 'name' => 'Akyemansa', 'capital' => 'Ofoase'],
                ['region_id' => 7, 'name' => 'Asene Manso Akroso', 'capital' => 'Manso'],
                ['region_id' => 7, 'name' => 'Asuogyaman', 'capital' => 'Atimpoku'],
                ['region_id' => 7, 'name' => 'Atiwa East', 'capital' => 'Anyinam'],
                ['region_id' => 7, 'name' => 'Atiwa West', 'capital' => 'Kwabeng'],
                ['region_id' => 7, 'name' => 'Ayensuano', 'capital' => 'Coaltar'],
                ['region_id' => 7, 'name' => 'Birim Central Municipal', 'capital' => 'Akim Oda'],
                ['region_id' => 7, 'name' => 'Birim North', 'capital' => 'New Abirem'],
                ['region_id' => 7, 'name' => 'Birim South', 'capital' => 'Akim Swedru'],
                ['region_id' => 7, 'name' => 'Denkyembour', 'capital' => 'Akwatia'],
                ['region_id' => 7, 'name' => 'Fanteakwa North', 'capital' => 'Begoro'],
                ['region_id' => 7, 'name' => 'Fanteakwa South', 'capital' => 'Osino'],
                ['region_id' => 7, 'name' => 'Kwaebibirem Municipal', 'capital' => 'Kade'],
                ['region_id' => 7, 'name' => 'Kwahu Afram Plains North', 'capital' => 'Donkorkrom'],
                ['region_id' => 7, 'name' => 'Kwahu Afram Plains South', 'capital' => 'Tease'],
                ['region_id' => 7, 'name' => 'Kwahu East', 'capital' => 'Abetifi'],
                ['region_id' => 7, 'name' => 'Kwahu South', 'capital' => 'Mpraeso'],
                ['region_id' => 7, 'name' => 'Kwahu West Municipal', 'capital' => 'Nkawkaw'],
                ['region_id' => 7, 'name' => 'Lower Manya Krobo Municipal', 'capital' => 'Krobo Odumase'],
                ['region_id' => 7, 'name' => 'New Juaben North Municipal', 'capital' => 'Effiduase'],
                ['region_id' => 7, 'name' => 'New Juaben South Municipal', 'capital' => 'Koforidua'],
                ['region_id' => 7, 'name' => 'Nsawam Adoagyire Municipal', 'capital' => 'Nsawam'],
                ['region_id' => 7, 'name' => 'Okere', 'capital' => 'Adukrom'],
                ['region_id' => 7, 'name' => 'Suhum Municipal', 'capital' => 'Suhum'],
                ['region_id' => 7, 'name' => 'Upper Manya Krobo', 'capital' => 'Asesewa'],
                ['region_id' => 7, 'name' => 'Upper West', 'capital' => 'Akim Adeiso'],
                ['region_id' => 7, 'name' => 'West Akim Municipal', 'capital' => 'Asamankese'],
                ['region_id' => 7, 'name' => 'Yilo Krobo Municipal', 'capital' => 'Somanya'],
                ['region_id' => 8, 'name' => 'Bunkpurugu Nyankpanduri', 'capital' => 'Bunkpurugu'],
                ['region_id' => 8, 'name' => 'Chereponi', 'capital' => 'Chereponi'],
                ['region_id' => 8, 'name' => 'East Mamprusi Municipal', 'capital' => 'Nalerigu'],
                ['region_id' => 8, 'name' => 'Mamprugu Moagduri', 'capital' => 'Yagaba'],
                ['region_id' => 8, 'name' => 'West Mamprusi Municipal', 'capital' => 'Walewale '],
                ['region_id' => 8, 'name' => 'Yunyoo Nasuan', 'capital' => 'Yunyoo'],
                ['region_id' => 9, 'name' => 'Gushegu Municipal', 'capital' => 'Gushegu'],
                ['region_id' => 9, 'name' => 'Karaga', 'capital' => 'Karaga'],
                ['region_id' => 9, 'name' => 'Kpandai', 'capital' => 'Kpandai'],
                ['region_id' => 9, 'name' => 'Kumbungu', 'capital' => 'Kumbungu'],
                ['region_id' => 9, 'name' => 'Mion', 'capital' => 'Sang'],
                ['region_id' => 9, 'name' => 'Nanton', 'capital' => 'Nanton'],
                ['region_id' => 9, 'name' => 'Nanumba North Municipal', 'capital' => 'Bimbilla'],
                ['region_id' => 9, 'name' => 'Nanumba South', 'capital' => 'Wulensi'],
                ['region_id' => 9, 'name' => 'Saboba', 'capital' => 'Saboba'],
                ['region_id' => 9, 'name' => 'Sagnarigu Municipal', 'capital' => 'Sagnarigu'],
                ['region_id' => 9, 'name' => 'Savelugu Municipal', 'capital' => 'Savelugu'],
                ['region_id' => 9, 'name' => 'Tamale Metropolitan', 'capital' => 'Tamale'],
                ['region_id' => 9, 'name' => 'Tatale Sanguli', 'capital' => 'Tatale'],
                ['region_id' => 9, 'name' => 'Tolon', 'capital' => 'Tolon'],
                ['region_id' => 9, 'name' => 'Yendi Municipal', 'capital' => 'Yendi'],
                ['region_id' => 9, 'name' => 'Zabzug', 'capital' => 'Zabzugu'],
                ['region_id' => 10, 'name' => 'Biakoye', 'capital' => 'Nkonya Ahenkro'],
                ['region_id' => 10, 'name' => 'Guan', 'capital' => 'Likpe Mate'],
                ['region_id' => 10, 'name' => 'Jasikan', 'capital' => 'Jasikan'],
                ['region_id' => 10, 'name' => 'Kadjebi', 'capital' => 'Kadjebi'],
                ['region_id' => 10, 'name' => 'Krachi East Municipal', 'capital' => 'Dambai'],
                ['region_id' => 10, 'name' => 'Krachi Nchumuru', 'capital' => 'Chinderi'],
                ['region_id' => 10, 'name' => 'Krachi West', 'capital' => 'Kete Krachi'],
                ['region_id' => 10, 'name' => 'Nkwanta North', 'capital' => 'Kpassa'],
                ['region_id' => 10, 'name' => 'Nkwanta South Municipal', 'capital' => 'Nkwanta'],
                ['region_id' => 11, 'name' => 'Bole', 'capital' => 'Bole'],
                ['region_id' => 11, 'name' => 'Central Gonja', 'capital' => 'Buipe'],
                ['region_id' => 11, 'name' => 'East Gonja Municipal', 'capital' => 'Salaga'],
                ['region_id' => 11, 'name' => 'North Gonja', 'capital' => 'Daboya'],
                ['region_id' => 11, 'name' => 'North East Gonja', 'capital' => 'Kpalbe'],
                ['region_id' => 11, 'name' => 'Sawla Tuna Kalba', 'capital' => 'Sawla'],
                ['region_id' => 11, 'name' => 'West Gonja Municipal', 'capital' => 'Damongo'],
                ['region_id' => 12, 'name' => 'Bawku Municipal', 'capital' => 'Bawku'],
                ['region_id' => 12, 'name' => 'Bawku West', 'capital' => 'Zebilla'],
                ['region_id' => 12, 'name' => 'Binduri', 'capital' => 'Binduri'],
                ['region_id' => 12, 'name' => 'Bolgatanga East', 'capital' => 'Zuarungu'],
                ['region_id' => 12, 'name' => 'Bolgatanga Municipal', 'capital' => 'Bolgatanga'],
                ['region_id' => 12, 'name' => 'Bongo', 'capital' => 'Bongo'],
                ['region_id' => 12, 'name' => 'Builsa North Municipal', 'capital' => 'Sandema'],
                ['region_id' => 12, 'name' => 'Builsa South', 'capital' => 'Fumbisi'],
                ['region_id' => 12, 'name' => 'Garu', 'capital' => 'Garu'],
                ['region_id' => 12, 'name' => 'Kassena Nankana Municipal', 'capital' => 'Navrongo'],
                ['region_id' => 12, 'name' => 'Kassena Nankana West', 'capital' => 'Paga'],
                ['region_id' => 12, 'name' => 'Nabdam', 'capital' => 'Nangodi'],
                ['region_id' => 12, 'name' => 'Pusiga', 'capital' => 'Pusiga'],
                ['region_id' => 12, 'name' => 'Talensi', 'capital' => 'Tongo'],
                ['region_id' => 12, 'name' => 'Tempane', 'capital' => 'Tempane'],
                ['region_id' => 13, 'name' => 'Daffiama Bussie Issa', 'capital' => 'Issa'],
                ['region_id' => 13, 'name' => 'Jirapa Municipal', 'capital' => 'Jirapa'],
                ['region_id' => 13, 'name' => 'Lambussie Karni', 'capital' => 'Lambussie'],
                ['region_id' => 13, 'name' => 'Lawra Municipal', 'capital' => 'Lawra'],
                ['region_id' => 13, 'name' => 'Nadowli Kaleo', 'capital' => 'Nadowli'],
                ['region_id' => 13, 'name' => 'Nandom Municipal', 'capital' => 'Nandom'],
                ['region_id' => 13, 'name' => 'Sissala East Municipal', 'capital' => 'Tumu'],
                ['region_id' => 13, 'name' => 'Sissala West', 'capital' => 'Gwollu'],
                ['region_id' => 13, 'name' => 'Wa East', 'capital' => 'Funsi'],
                ['region_id' => 13, 'name' => 'Wa Municipal', 'capital' => 'Wa'],
                ['region_id' => 13, 'name' => 'Wa West', 'capital' => 'Wechiau'],
                ['region_id' => 14, 'name' => 'Adaklu', 'capital' => 'Adaklu Waya'],
                ['region_id' => 14, 'name' => 'Afadzato South', 'capital' => 'Ve Golokwati'],
                ['region_id' => 14, 'name' => 'Agotime Ziope', 'capital' => 'Kpetoe'],
                ['region_id' => 14, 'name' => 'Akatsi North', 'capital' => 'Ave Dakpa'],
                ['region_id' => 14, 'name' => 'Akatsi South', 'capital' => 'Akatsi'],
                ['region_id' => 14, 'name' => 'Anloga', 'capital' => 'Anloga'],
                ['region_id' => 14, 'name' => 'Central Tongu', 'capital' => 'Adidome'],
                ['region_id' => 14, 'name' => 'Ho Municipal', 'capital' => 'Ho'],
                ['region_id' => 14, 'name' => 'Ho West', 'capital' => 'Dzolokpuita'],
                ['region_id' => 14, 'name' => 'Hohoe Municipal', 'capital' => 'Hohoe'],
                ['region_id' => 14, 'name' => 'Keta Municipal', 'capital' => 'Keta'],
                ['region_id' => 14, 'name' => 'Ketu North Municipal', 'capital' => 'Dzodze'],
                ['region_id' => 14, 'name' => 'Ketu South Municipal', 'capital' => 'Denu'],
                ['region_id' => 14, 'name' => 'Kpando Municipal', 'capital' => 'Kpando'],
                ['region_id' => 14, 'name' => 'North Dayi', 'capital' => 'Anfoega'],
                ['region_id' => 14, 'name' => 'North Tongu', 'capital' => 'Battor Dugame'],
                ['region_id' => 14, 'name' => 'South Dayi', 'capital' => 'Kpeve'],
                ['region_id' => 14, 'name' => 'South Tongu', 'capital' => 'Sogakope'],
                ['region_id' => 15, 'name' => 'Ahanta West Municipal', 'capital' => 'Agona Ahanta'],
                ['region_id' => 15, 'name' => 'Amenfi Central', 'capital' => 'Manso Amenfi'],
                ['region_id' => 15, 'name' => 'Amenfi West Municipal', 'capital' => 'Asankragua'],
                ['region_id' => 15, 'name' => 'Effia Kwesimintsim Municipal', 'capital' => 'Kwesimintsim'],
                ['region_id' => 15, 'name' => 'Ellembelle', 'capital' => 'Nkroful'],
                ['region_id' => 15, 'name' => 'Jomoro Municipal', 'capital' => 'Half Assini'],
                ['region_id' => 15, 'name' => 'Mpohor', 'capital' => 'Mpohor'],
                ['region_id' => 15, 'name' => 'Nzema East Municipal', 'capital' => 'Axim'],
                ['region_id' => 15, 'name' => 'Prestea-Huni Valley Municipal', 'capital' => 'Prestea'],
                ['region_id' => 15, 'name' => 'Sekondi Takoradi Metropolitan', 'capital' => 'Sekondi-Takoradi'],
                ['region_id' => 15, 'name' => 'Shama', 'capital' => 'Shama'],
                ['region_id' => 15, 'name' => 'Tarkwa-Nsuaem Municipal', 'capital' => 'Tarkwa'],
                ['region_id' => 15, 'name' => 'Wassa Amenfi East Municipal', 'capital' => 'Wassa-Akropong'],
                ['region_id' => 15, 'name' => 'Wassa East', 'capital' => 'Daboase'],
                ['region_id' => 16, 'name' => 'Aowin Municipal', 'capital' => 'Enchi'],
                ['region_id' => 16, 'name' => 'Bia East', 'capital' => 'Sefwi Adabokrom'],
                ['region_id' => 16, 'name' => 'Bia West', 'capital' => 'Essam Debiso '],
                ['region_id' => 16, 'name' => 'Bibiani Anhwiaso Bekwai Municipal', 'capital' => 'Bibiani'],
                ['region_id' => 16, 'name' => 'Bodi', 'capital' => 'Sefwi Bodi'],
                ['region_id' => 16, 'name' => 'Juaboso', 'capital' => 'Juaboso'],
                ['region_id' => 16, 'name' => 'Sefwi Akontombr', 'capital' => 'Sefwi Akontombra'],
                ['region_id' => 16, 'name' => 'Sefwi Wiawso Municipal', 'capital' => 'Sefwi Wiawso'],
                ['region_id' => 16, 'name' => 'Suaman', 'capital' => 'Dadieso'],
            ]
        );
    }
}
