<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('offices')->insert([
            ['id' => 1,  'name' => 'Headquarters',   'type' => 'headquarters', 'district_id' => 47],
            ['id' => 2,  'name' => 'Annex',          'type' => 'annex',        'district_id' => 47],
            ['id' => 3,  'name' => 'Ashanti',        'type' => 'regional',     'district_id' => 28],
            ['id' => 4,  'name' => 'Greater Accra',  'type' => 'regional',     'district_id' => 47],
            ['id' => 5,  'name' => 'Central',        'type' => 'regional',     'district_id' => 112],
            ['id' => 6,  'name' => 'Eastern',        'type' => 'regional',     'district_id' => 149],
            ['id' => 7,  'name' => 'Volta',          'type' => 'regional',     'district_id' => 228],
            ['id' => 8,  'name' => 'Western',        'type' => 'regional',     'district_id' => 248],
            ['id' => 9,  'name' => 'Western North',  'type' => 'regional',     'district_id' => 260],
            ['id' => 10, 'name' => 'North East',     'type' => 'regional',     'district_id' => 195],
            ['id' => 11, 'name' => 'Northern',       'type' => 'regional',     'district_id' => 174],
            ['id' => 12, 'name' => 'Oti',            'type' => 'regional',     'district_id' => 183],
            ['id' => 13, 'name' => 'Savannah',       'type' => 'regional',     'district_id' => 194],
            ['id' => 14, 'name' => 'Upper East',     'type' => 'regional',     'district_id' => 199],
            ['id' => 15, 'name' => 'Upper West',     'type' => 'regional',     'district_id' => 219],
            ['id' => 16, 'name' => 'Ahafo',          'type' => 'regional',     'district_id' => 73],
            ['id' => 17, 'name' => 'Bono',           'type' => 'regional',     'district_id' => 87],
            ['id' => 18, 'name' => 'Bono East',      'type' => 'regional',     'district_id' => 100],
            ['id' => 19, 'name' => 'Effiduase', 'type' => 'district', 'district_id' => 40],
            ['id' => 20, 'name' => 'Offinso',   'type' => 'district', 'district_id' => 34],
            ['id' => 21, 'name' => 'Obuasi',    'type' => 'district', 'district_id' => 33],
            ['id' => 22, 'name' => 'Konongo',   'type' => 'district', 'district_id' => 13],
            ['id' => 23, 'name' => 'Bekwai',    'type' => 'district', 'district_id' => 22],
            ['id' => 24, 'name' => 'Tepa',      'type' => 'district', 'district_id' => 6],
            ['id' => 25, 'name' => 'Mampong',   'type' => 'district', 'district_id' => 31],
            ['id' => 26, 'name' => 'Agona',     'type' => 'district', 'district_id' => 42],
            ['id' => 27, 'name' => 'TEMA', 'type' => 'district', 'district_id' => 70],
            ['id' => 28, 'name' => 'DODOWA', 'type' => 'district', 'district_id' => 69],
            ['id' => 29, 'name' => 'Agona - Swedru', 'type' => 'district', 'district_id' => 104],
            ['id' => 30, 'name' => 'Winneaba', 'type' => 'district', 'district_id' => 113],
            ['id' => 31, 'name' => 'Elmina', 'type' => 'district', 'district_id' => 118],
            ['id' => 32, 'name' => 'Twifo-Praso', 'type' => 'district', 'district_id' => 120],
            ['id' => 33, 'name' => 'Apam', 'type' => 'district', 'district_id' => 117],
            ['id' => 34, 'name' => 'Assin-Fosu', 'type' => 'district', 'district_id' => 107],
            ['id' => 35, 'name' => 'Dunkwa on Offin', 'type' => 'district', 'district_id' => 122],
            ['id' => 36, 'name' => 'Saltpond', 'type' => 'district', 'district_id' => 119],
            ['id' => 37, 'name' => 'Akim Oda', 'type' => 'district', 'district_id' => 135],
            ['id' => 38, 'name' => 'Asamankese', 'type' => 'district', 'district_id' => 155],
            ['id' => 39, 'name' => 'Kibi', 'type' => 'district', 'district_id' => 125],
            ['id' => 40, 'name' => 'Akropong', 'type' => 'district', 'district_id' => 127],
            ['id' => 41, 'name' => 'Nsawam', 'type' => 'district', 'district_id' => 150],
            ['id' => 42, 'name' => 'Odumase - Krobo', 'type' => 'district', 'district_id' => 147],
            ['id' => 43, 'name' => 'Nkawkaw', 'type' => 'district', 'district_id' => 146],
            ['id' => 44, 'name' => 'Hohoe',     'type' => 'district', 'district_id' => 230],
            ['id' => 45, 'name' => 'Kpando',    'type' => 'district', 'district_id' => 234],
            ['id' => 46, 'name' => 'Denu',      'type' => 'district', 'district_id' => 233],
            ['id' => 47, 'name' => 'Keta',      'type' => 'district', 'district_id' => 231],
            ['id' => 48, 'name' => 'Sogakope',  'type' => 'district', 'district_id' => 238],
            ['id' => 49, 'name' => 'Sekondi',      'type' => 'district', 'district_id' => 248],
            ['id' => 50, 'name' => 'Half Assini',  'type' => 'district', 'district_id' => 244],
            ['id' => 51, 'name' => 'Tarkwa',       'type' => 'district', 'district_id' => 250],
            ['id' => 52, 'name' => 'Asankragwa',   'type' => 'district', 'district_id' => 241],
            ['id' => 53, 'name' => 'Axim',         'type' => 'district', 'district_id' => 246],
            ['id' => 54, 'name' => 'Bibiani',        'type' => 'district', 'district_id' => 256],
            ['id' => 55, 'name' => 'Enchi',          'type' => 'district', 'district_id' => 253],
            ['id' => 56, 'name' => 'Sefwi Wiawso',   'type' => 'district', 'district_id' => 260],
            ['id' => 57, 'name' => 'Gambaga',        'type' => 'district', 'district_id' => 159],
            ['id' => 58, 'name' => 'Gushegu',   'type' => 'district', 'district_id' => 163],
            ['id' => 59, 'name' => 'Bimbilla',  'type' => 'district', 'district_id' => 169],
            ['id' => 60, 'name' => 'Yendi',     'type' => 'district', 'district_id' => 177],
            ['id' => 61, 'name' => 'Savelugu',  'type' => 'district', 'district_id' => 173],
            ['id' => 62, 'name' => 'Dambai',         'type' => 'district', 'district_id' => 183],
            ['id' => 63, 'name' => 'Jasikan',        'type' => 'district', 'district_id' => 181],
            ['id' => 64, 'name' => 'Nkwanta',        'type' => 'district', 'district_id' => 187],
            ['id' => 65, 'name' => 'Kete Krachi',    'type' => 'district', 'district_id' => 185],
            ['id' => 66, 'name' => 'Damongo',        'type' => 'district', 'district_id' => 194],
            ['id' => 67, 'name' => 'Bole',           'type' => 'district', 'district_id' => 188],
            ['id' => 68, 'name' => 'Salaga',         'type' => 'district', 'district_id' => 190],
            ['id' => 69, 'name' => 'Navrongo',       'type' => 'district', 'district_id' => 204],
            ['id' => 70, 'name' => 'Bawku',          'type' => 'district', 'district_id' => 195],
            ['id' => 71, 'name' => 'Zebilla',        'type' => 'district', 'district_id' => 196],
            ['id' => 72, 'name' => 'Jirapa',         'type' => 'district', 'district_id' => 211],
            ['id' => 73, 'name' => 'Lawra',          'type' => 'district', 'district_id' => 213],
            ['id' => 74, 'name' => 'Tumu',           'type' => 'district', 'district_id' => 216],
            ['id' => 75, 'name' => 'Goaso',          'type' => 'district', 'district_id' => 73],
            ['id' => 76, 'name' => 'Bechem',         'type' => 'district', 'district_id' => 78],
            ['id' => 77, 'name' => 'Dormaa Ahenkro', 'type' => 'district', 'district_id' => 82],
            ['id' => 78, 'name' => 'Drobo',          'type' => 'district', 'district_id' => 86],
            ['id' => 79, 'name' => 'Wenchi',         'type' => 'district', 'district_id' => 90],
            ['id' => 80, 'name' => 'Kintampo',       'type' => 'district', 'district_id' => 92],
            ['id' => 81, 'name' => 'Atebubu',        'type' => 'district', 'district_id' => 91],
            ['id' => 82, 'name' => 'MDAs Category A',        'type' => 'branch', 'district_id' => 47],
            ['id' => 83, 'name' => 'MDAs Category B',        'type' => 'branch', 'district_id' => 47],
            ['id' => 84, 'name' => 'MDAs Category C',        'type' => 'branch', 'district_id' => 47],
            ['id' => 85, 'name' => 'OTHER/SPECIAL AUDITS',   'type' => 'branch', 'district_id' => 47],
            ['id' => 86, 'name' => 'Universities',           'type' => 'branch', 'district_id' => 47],
            ['id' => 87, 'name' => 'BANK OF GHANA',          'type' => 'branch', 'district_id' => 47],
            ['id' => 88, 'name' => 'TECHNICAL UNIVERSITY AUDIT', 'type' => 'branch', 'district_id' => 47],
            ['id' => 89,  'name' => 'Ministry of Food and Agriculture', 'type' => 'branch', 'district_id' => 47],
            ['id' => 90,  'name' => 'Ministry of Environment, Science and Technology & Innovation', 'type' => 'branch', 'district_id' => 47],
            ['id' => 91,  'name' => 'Ministry of Energy', 'type' => 'branch', 'district_id' => 47],
            ['id' => 92,  'name' => 'Ministry of Fisheries Aquaculture development', 'type' => 'branch', 'district_id' => 47],
            ['id' => 93,  'name' => 'Ministry of Transport', 'type' => 'branch', 'district_id' => 47],
            ['id' => 94,  'name' => 'Min. of Sanitation and Water Resources', 'type' => 'branch', 'district_id' => 47],
            ['id' => 95,  'name' => 'Ministry of Communication', 'type' => 'branch', 'district_id' => 47],
            ['id' => 96,  'name' => 'Ministry of Works and Housing', 'type' => 'branch', 'district_id' => 47],
            ['id' => 97,  'name' => 'Ministry of Roads and Highways', 'type' => 'branch', 'district_id' => 47],
            ['id' => 98,  'name' => 'Ministry of Railway Development', 'type' => 'branch', 'district_id' => 47],
            ['id' => 99,  'name' => 'Ministry of Finance', 'type' => 'branch', 'district_id' => 47],
            ['id' => 100, 'name' => 'Ministry of Local Government and Rural Development', 'type' => 'branch', 'district_id' => 47],
            ['id' => 101, 'name' => 'Ministry of Lands and Natural Resources', 'type' => 'branch', 'district_id' => 47],
            ['id' => 102, 'name' => 'Ministry of Trade and Industry', 'type' => 'branch', 'district_id' => 47],
            ['id' => 103, 'name' => 'Ministry of Tourism, Arts and Culture', 'type' => 'branch', 'district_id' => 47],
            ['id' => 104, 'name' => 'Ministry of Intercity and Zongo Development', 'type' => 'branch', 'district_id' => 47],
            ['id' => 105, 'name' => 'GOVERNMENT MACHINERY', 'type' => 'branch', 'district_id' => 47],
            ['id' => 106, 'name' => 'Ministry of Special Development. Initiative', 'type' => 'branch', 'district_id' => 47],
            ['id' => 107, 'name' => 'Ministry of Regional Organisation & Development', 'type' => 'branch', 'district_id' => 47],
            ['id' => 108, 'name' => 'Ministry of Monitoring and Evaluation', 'type' => 'branch', 'district_id' => 47],
            ['id' => 109, 'name' => 'Ministry of Foreign Affairs', 'type' => 'branch', 'district_id' => 47],
            ['id' => 110, 'name' => 'Ministry of Information', 'type' => 'branch', 'district_id' => 47],
            ['id' => 111, 'name' => 'MINISTRY OF PARLIAMENTARY AFFAIRS', 'type' => 'branch', 'district_id' => 47],
            ['id' => 112, 'name' => 'PAYROLL AUDITS', 'type' => 'branch', 'district_id' => 47],
            ['id' => 113, 'name' => 'Pension Audit', 'type' => 'branch', 'district_id' => 47],
            ['id' => 114, 'name' => 'GRA CUSTOMS', 'type' => 'branch', 'district_id' => 47],
            ['id' => 115, 'name' => 'PUBLIC ACCOUNTS', 'type' => 'branch', 'district_id' => 47],
            ['id' => 116, 'name' => 'Ministry of Interior', 'type' => 'branch', 'district_id' => 47],
            ['id' => 117, 'name' => 'Ghana National Fire Service', 'type' => 'branch', 'district_id' => 47],
            ['id' => 118, 'name' => 'Ghana Police Service', 'type' => 'branch', 'district_id' => 47],
            ['id' => 119, 'name' => 'Ghana Prisons Service', 'type' => 'branch', 'district_id' => 47],
            ['id' => 120, 'name' => 'Ghana Immigration Service', 'type' => 'branch', 'district_id' => 47],
            ['id' => 121, 'name' => 'MINISTRY OF JUSTICE AND ATTORNEY-GENERAL', 'type' => 'branch', 'district_id' => 47],
            ['id' => 122, 'name' => 'Ministry of Defence', 'type' => 'branch', 'district_id' => 47],
            ['id' => 123, 'name' => 'MINISTRY OF EDUCATION', 'type' => 'branch', 'district_id' => 47],
            ['id' => 124, 'name' => 'MINISTRY OF YOUTH AND SPORTS', 'type' => 'branch', 'district_id' => 47],
            ['id' => 125, 'name' => 'Ministry of Employment and Labour Relations', 'type' => 'branch', 'district_id' => 47],
            ['id' => 126, 'name' => 'Ministry of Gender, Children and Social Protection', 'type' => 'branch', 'district_id' => 47],
            ['id' => 127, 'name' => 'Ministry of Chieftaincy and Religious Affairs', 'type' => 'branch', 'district_id' => 47],
            ['id' => 128, 'name' => 'Ministry of Health', 'type' => 'branch', 'district_id' => 47],
            ['id' => 129, 'name' => 'Performance Audit', 'type' => 'unit', 'district_id' => 47],
            ['id' => 130, 'name' => 'IT Audit', 'type' => 'unit', 'district_id' => 47],

        ]);
    }
}
