<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('units')->insert(
            [
                ['name' => 'Kumasi A', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Kumasi B', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Kumasi C', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Kunasi D', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'KMA', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Effiduase', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Offinso', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Obuasi', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Konongo', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Bekwai', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Tepa', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Mampong', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Agona', 'office_id' => 3, 'type' => 'district', 'department_id' => 1],
                ['name' => 'ACCRA A', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'ACCRA B', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'ACCRA C', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'AMA', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'TEMA', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'DODOWA', 'office_id' => 4, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Cape Coast District A', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Cape Coast District B', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Cape Coast District C', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Agona - Swedru', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Winneaba', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Elmina', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Twifo-Praso', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Apam', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Assin-Fosu', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Dunkwa on Offin', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Saltpond', 'office_id' => 5, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Koforidua A', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Koforidua B', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Koforidua C', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Akim Oda', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Asamankese', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Kibi', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Akropong', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Nsawam', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Odumase - Krobo', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Nkawkaw', 'office_id' => 6, 'type' => 'district', 'department_id' => 1],
                ['name' => 'HO A', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'HO B', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'HO C', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'HOHOE', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'KPANDO', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'DENU', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'KETA', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'SOGAKOPE', 'office_id' => 7, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Takoradi A', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Takoradi B', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Sekondi A', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Sekondi B', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Half Assini', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Tarkwa', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Asankragwa', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Axim', 'office_id' => 8, 'type' => 'district', 'department_id' => 1],
                ['name' => 'Bibiani', 'office_id' => 9, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Enchi', 'office_id' => 9, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Sefwi Wiawso', 'office_id' => 9, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Gambaga', 'office_id' => 10, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Tamale A', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Tamale B', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Tamale C', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Gushegu', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bimbilla', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Yendi', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Savelugu', 'office_id' => 11, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Dambai', 'office_id' => 12, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Jasikan', 'office_id' => 12, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Nkwanta', 'office_id' => 12, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Kete Krachi', 'office_id' => 12, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Damongo', 'office_id' => 13, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bole', 'office_id' => 13, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Salaga', 'office_id' => 13, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bolga A', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bolga B', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bolga C', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Navrongo', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bawku', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Zebilla', 'office_id' => 14, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Wa A', 'office_id' => 15, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Wa B', 'office_id' => 15, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Jirapa', 'office_id' => 15, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Lawra', 'office_id' => 15, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Tumu', 'office_id' => 15, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Goaso', 'office_id' => 16, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Bechem', 'office_id' => 16, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Sunyani A', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Sunyani B', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Sunyani C', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Dormaa Ahenkro', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Drobo', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Wenchi', 'office_id' => 17, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Techiman', 'office_id' => 18, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Kintampo', 'office_id' => 18, 'type' => 'district', 'department_id' => 2],
                ['name' => 'Atebubu', 'office_id' => 18, 'type' => 'district', 'department_id' => 2],
                ['name' => 'MDAs Category A', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'MDAs Category B', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'MDAs Category C', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'OTHER/SPECIAL AUDITS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'Universities', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'BANK OF GHANA', 'office_id' => 1, 'type' => 'branch', 'department_id' => 4],
                ['name' => 'TECHNICAL UNIVERSITY AUDIT', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Food and Agriculture', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Environment, Science and Technology & Innovation', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Energy', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Fisheries Aquaculture development', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Transport', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Min. of Sanitation and Water Resources', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Communication', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Works and Housing', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Roads and Highways', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Railway Development', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Finance', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Local Government and Rural Development', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Lands and Natural Resources', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Trade and Industry', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Tourism, Arts and Culture', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Intercity and Zongo Development', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'GOVERNMENT MACHINERY', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Special Development. Initiative', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Regional Organisation & Development', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Monitoring and Evaluation', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Foreign Affairs', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Information', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'MINISTRY OF PARLIAMENTARY AFFAIRS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'PAYROLL AUDITS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Pension Audit', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'GRA CUSTOMS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'PUBLIC ACCOUNTS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Interior', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ghana National Fire Service', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ghana Police Service', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ghana Prisons Service', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ghana Immigration Service', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'MINISTRY OF JUSTICE AND ATTORNEY-GENERAL', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Defence', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'MINISTRY OF EDUCATION', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'MINISTRY OF YOUTH AND SPORTS', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Employment and Labour Relations', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Gender, Children and Social Protection', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Chieftaincy and Religious Affairs', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Ministry of Health', 'office_id' => 1, 'type' => 'branch', 'department_id' => 3],
                ['name' => 'Performance Audit', 'office_id' => 2, 'type' => 'unit', 'department_id' => 5],
                ['name' => 'IT Audit', 'office_id' => 1, 'type' => 'unit', 'department_id' => 5],

            ]
        );
    }
}
